//
//  Subjects.swift
//  NanoChallenge-MyFirstApp
//
//  Created by Gabriel Ferreira de Carvalho on 02/06/21.
//

import Foundation
import UIKit

enum Subject: String, CaseIterable {
    case differentFonts = "Font Usage"
    case tracking = "Tracking"
    case color = "Color"
    case size = "Size"
    case leading = "Leading"
    case kerning = "Kerning"
    case mixedWithColor = "Mixing with color"
    case centeringText = "Allignment"
    case hierachyAndConstrast = "Hierarchy"
    
    func wrongCard() -> Card {
        switch self {
        case .centeringText:
            return Card(
                subject: self.rawValue,
                isCorrect: false,
                cardImage: UIImage(named: "centering_W"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .color:
            return Card(
                subject: self.rawValue,
                isCorrect: false,
                cardImage: UIImage(named: "color_W"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .differentFonts:
            return Card(
                subject: self.rawValue,
                isCorrect: false,
                cardImage: UIImage(named: "differentFonts_W"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .hierachyAndConstrast:
            return Card(
                subject: self.rawValue,
                isCorrect: false,
                cardImage: UIImage(named: "hierarchy_W"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .kerning:
            return Card(
                subject: self.rawValue,
                isCorrect: false,
                cardImage: UIImage(named: "kerning_W"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .leading:
            return Card(
                subject: self.rawValue,
                isCorrect: false,
                cardImage: UIImage(named: "leading_W"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .mixedWithColor:
            return Card(
                subject: self.rawValue,
                isCorrect: false,
                cardImage: UIImage(named: "mixedWithColors_W"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .size:
            return Card(
                subject: self.rawValue,
                isCorrect: false,
                cardImage: UIImage(named: "size_W"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .tracking:
            return Card(
                subject: self.rawValue,
                isCorrect: false,
                cardImage: UIImage(named: "tracking_W"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
        }
    }
    
    func correctCard() -> Card {
        switch self {
        case .centeringText:
            return Card(
                subject: self.rawValue,
                isCorrect: true,
                cardImage: UIImage(named: "centering_C"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .color:
            return Card(
                subject: self.rawValue,
                isCorrect: true,
                cardImage: UIImage(named: "color_C"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .differentFonts:
            return Card(
                subject: self.rawValue,
                isCorrect: true,
                cardImage: UIImage(named: "differentFonts_C"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .hierachyAndConstrast:
            return Card(
                subject: self.rawValue,
                isCorrect: true,
                cardImage: UIImage(named: "hierarchy_C"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .kerning:
            return Card(
                subject: self.rawValue,
                isCorrect: true,
                cardImage: UIImage(named: "kerning_C"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .leading:
            return Card(
                subject: self.rawValue,
                isCorrect: true,
                cardImage: UIImage(named: "leading_C"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .mixedWithColor:
            return Card(
                subject: self.rawValue,
                isCorrect: true,
                cardImage: UIImage(named: "mixedWithColors_C"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .size:
            return Card(
                subject: self.rawValue,
                isCorrect: true,
                cardImage: UIImage(named: "size_C"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
            
        case .tracking:
            return Card(
                subject: self.rawValue,
                isCorrect: true,
                cardImage: UIImage(named: "tracking_C"),
                subjectExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                answerExplanation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit amet. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Arcu ac tortor dignissim convallis aenean et tortor at risus. Viverra tellus in hac habitasse. In mollis nunc sed id semper risus in. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. A pellentesque sit amet porttitor eget dolor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi leo urna molestie at elementum eu facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nunc eget lorem dolor sed. Turpis egestas pretium aenean pharetra magna ac placerat. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ipsum suspendisse ultrices gravida dictum.",
                userGetItRight: false)
        }
    }
    
}
